//
// News.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct News: Codable, JSONEncodable, Hashable {

    public var author: String?
    public var title: String?
    public var description: String?
    public var url: String
    public var source: String?
    public var image: String?
    public var category: String?
    public var language: String?
    public var country: String?
    public var publishedAt: String?

    public init(author: String? = nil, title: String? = nil, description: String? = nil, url: String, source: String? = nil, image: String? = nil, category: String? = nil, language: String? = nil, country: String? = nil, publishedAt: String? = nil) {
        self.author = author
        self.title = title
        self.description = description
        self.url = url
        self.source = source
        self.image = image
        self.category = category
        self.language = language
        self.country = country
        self.publishedAt = publishedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case author
        case title
        case description
        case url
        case source
        case image
        case category
        case language
        case country
        case publishedAt = "published_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(author, forKey: .author)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(url, forKey: .url)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(language, forKey: .language)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(publishedAt, forKey: .publishedAt)
    }
}

