//
// NewsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class NewsAPI {

    /**
     News List
     
     - parameter accessKey: (query) API key 
     - parameter sources: (query) News sources (CNN, BBC, etc.) (optional)
     - parameter categories: (query) News categories (business, sports, etc.) (optional)
     - parameter languages: (query) Language in two letters (optional)
     - parameter limit: (query) Number of results per page (optional)
     - parameter offset: (query) Pagination offset value (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getNews(accessKey: String, sources: String? = nil, categories: String? = nil, languages: String? = nil, limit: String? = nil, offset: String? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: NewsList?, _ error: Error?) -> Void)) -> RequestTask {
        return getNewsWithRequestBuilder(accessKey: accessKey, sources: sources, categories: categories, languages: languages, limit: limit, offset: offset).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     News List
     - GET /news
     - parameter accessKey: (query) API key 
     - parameter sources: (query) News sources (CNN, BBC, etc.) (optional)
     - parameter categories: (query) News categories (business, sports, etc.) (optional)
     - parameter languages: (query) Language in two letters (optional)
     - parameter limit: (query) Number of results per page (optional)
     - parameter offset: (query) Pagination offset value (optional)
     - returns: RequestBuilder<NewsList> 
     */
    open class func getNewsWithRequestBuilder(accessKey: String, sources: String? = nil, categories: String? = nil, languages: String? = nil, limit: String? = nil, offset: String? = nil) -> RequestBuilder<NewsList> {
        let localVariablePath = "/news"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "access_key": accessKey,
            "sources": sources,
            "categories": categories,
            "languages": languages,
            "limit": limit,
            "offset": offset,
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NewsList>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
